[package]
name = "marlinformat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.10.0", features = ["derive"] }
cozy-chess = "0.2.2"
